### ISSUE TITLE
ModuleNotFoundError: No module named 'interface'

### ISSUE THREAD

**Issue by jnswx** [CETC-TFAI/MaCA#1]
运行fight_mp.py后提示 
File "fight_mp.py", line 14, in <module>
    from interface import Environment
ModuleNotFoundError: No module named 'interface'

**Comment by leonfg** [comment]
> 
> 
> 运行fight_mp.py后提示
> File "fight_mp.py", line 14, in
> from interface import Environment
> ModuleNotFoundError: No module named 'interface'

If you run fight in cmd line, set the PYTHONPATH first (for linux and mac only):
```bash
cd MaCA
export PYTHONPATH=$(pwd)/environment:$PYTHONPATH
```
For pycharm, you can set /environment as source folder

**Comment by jnswx** [comment]
Thanks for your reply!.I have set /environment as source folder.I run 'fight_mp.py' in PyCharm,but it still prompt the same error. I run it in win7 x64,python3.7,pycharm2019

**Comment by leonfg** [comment]
> 
> 
> Thanks for your reply!.I have set /environment as source folder.I run 'fight_mp.py' in PyCharm,but it still prompt the same error. I run it in win7 x64,python3.7,pycharm2019

我我在win10上全新clone了一次，按流程设置后并没有出现你说的问题。
只能请你再次确认source root是否设置正确：
[](https://tva1.sinaimg.cn/large/007rAy9hgy1g2jvbhyb93j30z20ojwfa.jpg)
另外请检查工程是否下载完整，特别是environment路径是否存在interface.py文件。
如果一切都没问题，只好换个机器试试了。

**Comment by jnswx** [comment]
> > Thanks for your reply!.I have set /environment as source folder.I run 'fight_mp.py' in PyCharm,but it still prompt the same error. I run it in win7 x64,python3.7,pycharm2019
> 
> 我在win10上全新clone了一次，按流程设置后并没有出现你说的问题。
> 只能请你再次确认source root是否[设置正确](https://tva1.sinaimg.cn/large/007rAy9hgy1g2jvbhyb93j30z20ojwfa.jpg)：
> 另外请检查工程是否下载完整，特别是environment路径是否存在interface.py文件。
> 如果一切都没问题，只好换个机器试试了。

我换了Linux系统，终端运行和在pycharm中运行都可以，但是在pycharm中的terminal窗口运行依旧报同样的错误，即使已经设置了source root。

**Comment by leonfg** [comment]
@jnswx pycharm的terminal应该不遵循pycharm的环境设置，只是调用系统terminal。在pycharm终 terminal里再export一下pythonpath应该能解决。
