### ISSUE TITLE
能否支持下更高版本的python,比如3.8

### ISSUE THREAD

**Issue by gingkg** [CETC-TFAI/MaCA#17]
在Python 3.8，Pygame 1.9.6 下运行会报错：
Traceback (most recent call last):
  File "D:/RL/MaCA/fight_mp.py", line 14, in <module>
    from interface import Environment
  File "D:\RL\MaCA\environment\interface.py", line 15, in <module>
    from world.em_battle import BattleField
  File "D:\RL\MaCA\environment\world\__init__.py", line 1, in <module>
 __pyarmor__(__name__, __file__, b'\xec\x50\x8c\x64\x26\x42\xd6\x01\x10\x54\xca\x9c\xb6\x33\x81\x05\x30\xdb\x46\xb3\x6d\x0c\xa2\x2d\x19\xe2\x8f\xf9\x44\x25\xd5\x53\xc7\x67\x06\x76\x71\x8d\x42\xe2\xc3\xef\x00\x16\xa3\x91\x11\x67\x09\x92\x9a\x72\x18\xf6\x31\xbd\x95\x78\x69\xe0\x84\xc1\x30\x40\x93\x62\xc4\x8e\xd6\xf0\x0d\x5b\x82\x29\x55\x63\xd9\x3e\x7a\x4e\x40\xcb\xae\x0e\x9d\x45\x72\xa4\x22\x50\xc5\x00\x06\x2d\x29\xe5\xe1\x5f\xa6\xee\x04\xfd\x9f\xc1\x10\xe5\xd5\x07\xef\xb6\xee\x36\xcc\x39\x5c\xa0\xab\x6f\x6e\x9e\xb6\xf5\x42\x3f\x41\xeb\x1b\x0a\x07\xbe\x67\x3e\x0f\x8f\xe7\x61\x8a\xcf\x9b\xa3\x22\x07\xb0\x4c\xc0\x53\x6f\xf9\x0c\x1c\x61\xfa\xa0\x28\xa4', 1)
MemoryError
涉及加密代码，没法自行更改。
注：在Python 3.6，Pygame 1.9.6 测试没有问题。

**Comment by leonfg** [comment]
好的，我们尽量处理
