### ISSUE TITLE
好像是pyarmor的加密的部分出现的问题？求助！

### ISSUE THREAD

**Issue by CharlesPuth** [CETC-TFAI/MaCA#18]
D:\Conda\envs\fly\python.exe D:/pycharm_workplace/MaCA-master/train/simple/main.py
pygame 2.0.1 (SDL 2.0.14, Python 3.6.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:/pycharm_workplace/MaCA-master/train/simple/main.py", line 45, in <module>
    env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=RENDER)
  File "D:\pycharm_workplace\MaCA-master\environment\interface.py", line 53, in __init__
    side2_name=side2_name)
  File "<frozen environment.world.em_battle>", line 128, in __init__
  File "<frozen environment.render.render_pic>", line 29, in __init__
FileNotFoundError: No such file or directory.

Process finished with exit code 1
在运行main.py的时候出现了这个问题，感觉是加密的模块读取失误？想请您帮忙看看
另外，想请问license什么时候过期，我想在毕设的时候引用一下贵司的平台，担心到时候license过期了…

**Comment by CharlesPuth** [comment]
@leonfg 您好！求助QAQ

**Comment by leonfg** [comment]
目前没有设置过期时间。
不像是pyarmor的问题，但是没有显示file名称也许跟他有关系。如果你用fixrule能正常跑的话就不是平台本身的问题，还是跟agent相关的东西比如agent、model、construct、train里面有东西没有或者路径有问题

**Comment by CharlesPuth** [comment]
> 目前没有设置过期时间。
> 不像是pyarmor的问题，但是没有显示file名称也许跟他有关系。如果你用fixrule能正常跑的话就不是平台本身的问题，还是跟agent相关的东西比如agent、model、construct、train里面有东西没有或者路径有问题

好的！感谢您的解答！那如果我的论文想使用贵司的MaCA的平台，在引用处以以下形式注明：
Gao F , Chen S , Li M , et al. MaCA: a Multi-agent Reinforcement Learning Platform for Collective Intelligence[C]// 2019 IEEE 10th International Conference on Software Engineering and Service Science (ICSESS). IEEE, 2019.
就可以了吗？QWQ

**Comment by leonfg** [comment]
> 
> 
> > 目前没有设置过期时间。
> > 不像是pyarmor的问题，但是没有显示file名称也许跟他有关系。如果你用fixrule能正常跑的话就不是平台本身的问题，还是跟agent相关的东西比如agent、model、construct、train里面有东西没有或者路径有问题
> 
> 好的！感谢您的解答！那如果我的论文想使用贵司的MaCA的平台，在引用处以以下形式注明：
> Gao F , Chen S , Li M , et al. MaCA: a Multi-agent Reinforcement Learning Platform for Collective Intelligence[C]// 2019 IEEE 10th International Conference on Software Engineering and Service Science (ICSESS). IEEE, 2019.
> 就可以了吗？QWQ

OK

**Comment by CharlesPuth** [comment]
> > > 目前没有设置过期时间。
> > > 不像是pyarmor的问题，但是没有显示file名称也许跟他有关系。如果你用fixrule能正常跑的话就不是平台本身的问题，还是跟agent相关的东西比如agent、model、construct、train里面有东西没有或者路径有问题
> > 
> > 
> > 好的！感谢您的解答！那如果我的论文想使用贵司的MaCA的平台，在引用处以以下形式注明：
> > Gao F , Chen S , Li M , et al. MaCA: a Multi-agent Reinforcement Learning Platform for Collective Intelligence[C]// 2019 IEEE 10th International Conference on Software Engineering and Service Science (ICSESS). IEEE, 2019.
> > 就可以了吗？QWQ
> 
> OK

谢谢！！！！
