### ISSUE TITLE
提示 license failed，怎么解决

### ISSUE THREAD

**Issue by CargoHu** [CETC-TFAI/MaCA#3]
Traceback (most recent call last):
  File "Y:/demo/MaCA/fight_mp.py", line 14, in <module>
    from interface import Environment
  File "Y:\demo\MaCA\environment\interface.py", line 4, in <module>
    pyarmor_runtime()
  File "Y:\demo\MaCA\environment\pytransform.py", line 274, in pyarmor_runtime
    pyarmor_init(path)
  File "Y:\demo\MaCA\environment\pytransform.py", line 271, in pyarmor_init
    init_pytransform()
  File "Y:\demo\MaCA\environment\pytransform.py", line 72, in wrap
    raise PytransformError(format_message(errmsg, *args, **kwargs))
pytransform.PytransformError: b'License is expired\nCheck license failed\nInitialize pytransform failed'

**Comment by leonfg** [comment]
> 
> 
> Traceback (most recent call last):
> File "Y:/demo/MaCA/fight_mp.py", line 14, in
> from interface import Environment
> File "Y:\demo\MaCA\environment\interface.py", line 4, in
> pyarmor_runtime()
> File "Y:\demo\MaCA\environment\pytransform.py", line 274, in pyarmor_runtime
> pyarmor_init(path)
> File "Y:\demo\MaCA\environment\pytransform.py", line 271, in pyarmor_init
> init_pytransform()
> File "Y:\demo\MaCA\environment\pytransform.py", line 72, in wrap
> raise PytransformError(format_message(errmsg, *args, **kwargs))
> pytransform.PytransformError: b'License is expired\nCheck license failed\nInitialize pytransform failed'

更新一下

**Comment by sanshibayuan** [comment]
> > Traceback (most recent call last):
> > File "Y:/demo/MaCA/fight_mp.py", line 14, in
> > from interface import Environment
> > File "Y:\demo\MaCA\environment\interface.py", line 4, in
> > pyarmor_runtime()
> > File "Y:\demo\MaCA\environment\pytransform.py", line 274, in pyarmor_runtime
> > pyarmor_init(path)
> > File "Y:\demo\MaCA\environment\pytransform.py", line 271, in pyarmor_init
> > init_pytransform()
> > File "Y:\demo\MaCA\environment\pytransform.py", line 72, in wrap
> > raise PytransformError(format_message(errmsg, *args, **kwargs))
> > pytransform.PytransformError: b'License is expired\nCheck license failed\nInitialize pytransform failed'
> 
> 更新一下

遇到了同样的问题 请问是更新什么

**Comment by leonfg** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        如果你是git clone下载的，使用git pull命令更新如果你是直接下载的压缩包，重新下载一次。
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.7;
        }
    
_____________________Best Regards!Leon

        
    
     

    在2019年7月18日 20:13，Zhiyin Hong<notifications@github.com> 写道： 






Traceback (most recent call last):

File "Y:/demo/MaCA/fight_mp.py", line 14, in

from interface import Environment

File "Y:\demo\MaCA\environment\interface.py", line 4, in

pyarmor_runtime()

File "Y:\demo\MaCA\environment\pytransform.py", line 274, in pyarmor_runtime

pyarmor_init(path)

File "Y:\demo\MaCA\environment\pytransform.py", line 271, in pyarmor_init

init_pytransform()

File "Y:\demo\MaCA\environment\pytransform.py", line 72, in wrap

raise PytransformError(format_message(errmsg, *args, **kwargs))

pytransform.PytransformError: b'License is expired\nCheck license failed\nInitialize pytransform failed'



更新一下



遇到了同样的问题 请问是更新什么
