### ISSUE TITLE
Dose  the environment  support  algorithm   as A3C(Asynchronous Advantage Actor-Critic)?

### ISSUE THREAD

**Issue by nidao66** [CETC-TFAI/MaCA#4]
Hi, dose  the environment  support  algorithm   as A3C(Asynchronous Advantage Actor-Critic)?
or  support  parallel  training  net ?

**Comment by leonfg** [comment]
Yes.

**Comment by nidao66** [comment]
thank you for your answer  
but  i use  torch.multiprocessing   parallel training   . i  would  see  the erro  
**TypeError: can't pickle pygame.Surface objects**
import torch.multiprocessing as mp
1 class Worker(mp.Process):
2    def __init__(self,):
3   self.env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=RENDER)

the third line  would  be wrong
  File "C:\Users\m\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle pygame.Surface objects

would  i  change  the  Environment  config  or  sourcecode  to  slove this problem?

**Comment by leonfg** [comment]
> 
> 
> thank you for your answer
> but i use torch.multiprocessing parallel training . i would see the erro
> **TypeError: can't pickle pygame.Surface objects**
> import torch.multiprocessing as mp
> 1 class Worker(mp.Process):
> 2 def **init**(self,):
> 3 self.env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=RENDER)
> 
> the third line would be wrong
> File "C:\Users\m\Anaconda3\lib\multiprocessing\process.py", line 112, in start
> self._popen = self._Popen(self)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in **init**
> reduction.dump(process_obj, to_child)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> TypeError: can't pickle pygame.Surface objects
> 
> would i change the Environment config or sourcecode to slove this problem?

try render=False

**Comment by nidao66** [comment]
> thank you for your answer
> but i use torch.multiprocessing parallel training . i would see the erro
> TypeError: can't pickle pygame.Surface objects
> import torch.multiprocessing as mp
> 1 class Worker(mp.Process):
> 2 def init(self,):
> 3 self.env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=RENDER)
> the third line would be wrong
> File "C:\Users\m\Anaconda3\lib\multiprocessing\process.py", line 112, in start
> self._popen = self._Popen(self)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in init
> reduction.dump(process_obj, to_child)
> File "C:\Users\m\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> TypeError: can't pickle pygame.Surface objects
> would i change the Environment config or sourcecode to slove this problem?
> 
> try render=False

i had  try render=False
 it doesnt  work ，other  solution？  thank you for your help

**Comment by leonfg** [comment]
> 
> 
> > thank you for your answer
> > but i use torch.multiprocessing parallel training . i would see the erro
> > TypeError: can't pickle pygame.Surface objects
> > import torch.multiprocessing as mp
> > 1 class Worker(mp.Process):
> > 2 def init(self,):
> > 3 self.env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=RENDER)
> > the third line would be wrong
> > File "C:\Users\m\Anaconda3\lib\multiprocessing\process.py", line 112, in start
> > self._popen = self._Popen(self)
> > File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> > return _default_context.get_context().Process._Popen(process_obj)
> > File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> > return Popen(process_obj)
> > File "C:\Users\m\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in init
> > reduction.dump(process_obj, to_child)
> > File "C:\Users\m\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> > ForkingPickler(file, protocol).dump(obj)
> > TypeError: can't pickle pygame.Surface objects
> > would i change the Environment config or sourcecode to slove this problem?
> > try render=False
> 
> i had try render=False
> it doesnt work ，other solution？ thank you for your help

Could you please post your full code from beginning to make environment?

**Comment by nidao66** [comment]
`
import torch
import torch.nn as nn
from utils import v_wrap, set_init, push_and_pull, record
import torch.nn.functional as F
import torch.multiprocessing as mp
from shared_adam import SharedAdam
from agent.fix_rule_no_att.agent import Agent
from interface import Environment

MAP_PATH = 'maps/1000_1000_fighter10v10.map'


UPDATE_GLOBAL_ITER = 10
GAMMA = 0.9
MAX_EP = 4000
RENDER = False
MAX_EPOCH = 1000
BATCH_SIZE = 200
LR = 0.01                   # learning rate
EPSILON = 0.9               # greedy policy
GAMMA = 0.9                 # reward discount
TARGET_REPLACE_ITER = 100   # target update frequency
DETECTOR_NUM = 0
FIGHTER_NUM = 10
COURSE_NUM = 16
ATTACK_IND_NUM = (DETECTOR_NUM + FIGHTER_NUM) * 2 + 1 # long missile attack + short missile attack + no attack
ACTION_NUM = COURSE_NUM * ATTACK_IND_NUM
LEARN_INTERVAL = 100

blue_agent = Agent()
# get agent obs type
red_agent_obs_ind = 'a3c'
blue_agent_obs_ind = blue_agent.get_obs_ind()



class Net(nn.Module):
    def __init__(self, s_dim, a_dim):
        super(Net, self).__init__()
        self.s_dim = s_dim
        self.a_dim = a_dim
        self.pi1 = nn.Linear(s_dim, 200)
        self.pi2 = nn.Linear(200, a_dim)
        self.v1 = nn.Linear(s_dim, 100)
        self.v2 = nn.Linear(100, 1)
        set_init([self.pi1, self.pi2, self.v1, self.v2])
        self.distribution = torch.distributions.Categorical

    def forward(self, x):
        pi1 = F.relu6(self.pi1(x))
        logits = self.pi2(pi1)
        v1 = F.relu6(self.v1(x))
        values = self.v2(v1)
        return logits, values

    def choose_action(self, s):
        self.eval()
        logits, _ = self.forward(s)
        prob = F.softmax(logits, dim=1).data
        m = self.distribution(prob)
        return m.sample().numpy()[0]

    def loss_func(self, s, a, v_t):
        self.train()
        logits, values = self.forward(s)
        td = v_t - values
        c_loss = td.pow(2)
        
        probs = F.softmax(logits, dim=1)
        m = self.distribution(probs)
        exp_v = m.log_prob(a) * td.detach().squeeze()
        a_loss = -exp_v
        total_loss = (c_loss + a_loss).mean()
        return total_loss


class Worker(mp.Process):
    def __init__(self,  gnet, opt, global_ep, global_ep_r, res_queue, name):
        super(Worker, self).__init__()
        self.name = 'w%i' % name
        self.g_ep, self.g_ep_r, self.res_queue = global_ep, global_ep_r, res_queue
        self.gnet, self.opt = gnet, opt
        self.lnet = Net(1000, ACTION_NUM)           # local network
        self.env = Environment(MAP_PATH, red_agent_obs_ind, blue_agent_obs_ind, render=False)
    def run(self):
        total_step = 1
        while self.g_ep.value < MAX_EP:
            s = self.env.reset()
            buffer_s, buffer_a, buffer_r = [], [], []
            ep_r = 0.
            while True:
                if self.name == 'w0':
                    self.env.render()
                a = self.lnet.choose_action(v_wrap(s[None, :]))
                s_, r, done, _ = self.env.step(a)
                if done: r = -1
                ep_r += r
                buffer_a.append(a)
                buffer_s.append(s)
                buffer_r.append(r)

                if total_step % UPDATE_GLOBAL_ITER == 0 or done:  # update global and assign to local net
                    # sync
                    push_and_pull(self.opt, self.lnet, self.gnet, done, s_, buffer_s, buffer_a, buffer_r, GAMMA)
                    buffer_s, buffer_a, buffer_r = [], [], []

                    if done:  # done and print information
                        record(self.g_ep, self.g_ep_r, ep_r, self.res_queue, self.name)
                        break
                s = s_
                total_step += 1
        self.res_queue.put(None)


if __name__ == "__main__":
    gnet = Net(100, ACTION_NUM)
    gnet.share_memory()
    opt = SharedAdam(gnet.parameters(), lr=0.0001)
    global_ep, global_ep_r, res_queue = mp.Value('i', 0), mp.Value('d', 0.), mp.Queue()

    # parallel training
    workers = [Worker( gnet, opt, global_ep, global_ep_r, res_queue, i) for i in [1]]
    [w.start() for w in workers]
    res = []                    # record episode reward to plot
    while True:
        r = res_queue.get()
        if r is not None:
            res.append(r)
        else:
            break
    [w.join() for w in workers]

`
`Traceback (most recent call last):
  File "D:/MaCA-master/discrete_A3C.py", line 124, in <module>
    [w.start() for w in workers]
  File "D:/MaCA-master/discrete_A3C.py", line 124, in <listcomp>
    [w.start() for w in workers]
  File "C:\Users\m\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\m\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects`


i  refer to  the  a3c  pytorch  code    to  solve   CART-POLE game

**Comment by leonfg** [comment]
It's difficult to read your code with disordered format. Could you nest your code with markdown code block? Or send all the codes to leonfg83@gmail.com will be better.
From the error info I can tell that it is not a pygame problem, I have to execute the code to troubleshooting. And there are some coding error in Environment API calling, but it seems the failure is before these errors.

**Comment by nidao66** [comment]
> It's difficult to read your code with disordered format. Could you nest your code with markdown code block? Or send all the codes to leonfg83@gmail.com will be better.
> From the error info I can tell that it is not a pygame problem, I have to execute the code to troubleshooting. And there are some coding error in MaCA API calling, but it seems the failure is before these errors.

Thank  you . I will check the code.

**Comment by leonfg** [comment]
> 
> 
> > It's difficult to read your code with disordered format. Could you nest your code with markdown code block? Or send all the codes to [leonfg83@gmail.com](mailto:leonfg83@gmail.com) will be better.
> > From the error info I can tell that it is not a pygame problem, I have to execute the code to troubleshooting. And there are some coding error in MaCA API calling, but it seems the failure is before these errors.
> 
> Thank you . I will check the code.

So did you fix the multiprocess problem?
