### ISSUE TITLE
Inference GPU-trained model On CPU raise error

### ISSUE THREAD

**Issue by sanshibayuan** [CETC-TFAI/MaCA#5]
Hi there
I was able to train a model on GPU 
And the model was fine when inference on GPU
![image](https://user-images.githubusercontent.com/30117384/61590330-15ec1080-abea-11e9-8982-ddc8010f8abe.png)
 
But my GPU server does not have display access so I wanted to show the demo on my local CPU, but when I ran the code I met this problem
![image](https://user-images.githubusercontent.com/30117384/61590345-40d66480-abea-11e9-98b4-cebc59d326c1.png)

And as you know the files under environment are all encrypted so I have no idea what when wrong, can you shed some lights on me ? Thanks A lot !!!!!

**Comment by sanshibayuan** [comment]
Also, I ran the simple/DQN model and  trained with default parameters, and when I ran test I got the DQN agent crashed every time, Is there something I should pay attention to ?

**Comment by leonfg** [comment]
> 
> 
> Hi there
> I was able to train a model on GPU
> And the model was fine when inference on GPU
> ![image](https://user-images.githubusercontent.com/30117384/61590330-15ec1080-abea-11e9-8982-ddc8010f8abe.png)
> 
> But my GPU server does not have display access so I wanted to show the demo on my local CPU, but when I ran the code I met this problem
> ![image](https://user-images.githubusercontent.com/30117384/61590345-40d66480-abea-11e9-98b4-cebc59d326c1.png)
> 
> And as you know the files under environment are all encrypted so I have no idea what when wrong, can you shed some lights on me ? Thanks A lot !!!!!

"simple" is a demo code for homogeneous map 1000_1000_fighter10v10, it only provides fighter controlling. That is why env throw an error. If you pay attention to the execution log on your GPU server, simple crashed at the beginning, I am not sure why it crashed because it runs well in my GPU Platform, but crashing is the reason why env didn't report error. So please use the correct map and try again.

**Comment by sanshibayuan** [comment]
> "simple" is a demo code for homogeneous map "1000_1000_fighter10v10", it only provides fighter controlling. The env throws an error because there is no detector action data. So please use the correct map and try again.

Thanks for the nice reply! I now change the map in the fight.py file to  "1000_1000_fighter10v10", and used my trained model to test but I still got the crashed error...

**Comment by leonfg** [comment]
Sorry I deleted your question by mistake.
Your first picture shows simple crashed in GPU server, and in second picture it was OK. Do you mean it only crashes in GPU server?

**Comment by sanshibayuan** [comment]
> Sorry I deleted your reply by mistake.
> Your first picture shows simple crashed in GPU server, and in second picture it was OK. Do you mean it only crashes in your GPU server?

Sorry for the late reply. Let me get my problem straight:
1. The Simple/DQN model crushed on GPU with correct map everytime; 
2. Since I had another problem running the pretrained model on CPU would raise the error "list indices must be integers or slices, not tuple" as the picture says, I had to use the **replay.py** on CPU and it crushed everytime(the game was crushed I suppose).
3. I haven't try running the model on CPU because of the RAM memory problem.

**Comment by leonfg** [comment]
> 
> 
> > Sorry I deleted your reply by mistake.
> > Your first picture shows simple crashed in GPU server, and in second picture it was OK. Do you mean it only crashes in your GPU server?
> 
> Sorry for the late reply. Let me get my problem straight:
> 
>     1. The Simple/DQN model was training fine on GPU, but **crushed everytime when testing,**  with correct map everytime;
> 
>     2. Since I had another problem **testing the pretrained model on CPU would raise the error** "list indices must be integers or slices, not tuple" as the picture says, I had to use the **replay.py** on CPU and it crushed everytime(the game was crushed I suppose).
> 
>     3. I haven't try running the model on CPU because of the **RAM memory problem**.

I'm very sorry I can't solve your problem. I can't figure out how your problem came about. Considering that MaCA is running OK in our and dozens of competitor's environments, the only suggestion is to try other environments. Anyway, simple is only an example for agent coding, it's not a big deal if it can't run in your computer.

**Comment by sanshibayuan** [comment]
> > > Sorry I deleted your reply by mistake.
> > > Your first picture shows simple crashed in GPU server, and in second picture it was OK. Do you mean it only crashes in your GPU server?
> > 
> > 
> > Sorry for the late reply. Let me get my problem straight:
> > ```
> > 1. The Simple/DQN model was training fine on GPU, but **crushed everytime when testing,**  with correct map everytime;
> > 
> > 2. Since I had another problem **testing the pretrained model on CPU would raise the error** "list indices must be integers or slices, not tuple" as the picture says, I had to use the **replay.py** on CPU and it crushed everytime(the game was crushed I suppose).
> > 
> > 3. I haven't try running the model on CPU because of the **RAM memory problem**.
> > ```
> 
> I'm very sorry that I can't figure out how your problem came about. Considering that it is running OK in ours and dozens of competitor's environments, the only suggestion is to try other environments. Anyway, simple is only an example for agent coding, it's not a big deal if it can't run in your computer.

Thank you for the reply! I will try other environment and close this one
