### ISSUE TITLE
类似的环境问题请教

### ISSUE THREAD

**Issue by lee-github-2020** [CETC-TFAI/MaCA#8]
您好，我自学RL有一段时间了，因为对海战感兴趣，一直想把RL应用在海战上，但是gym上没有合适的环境，一直想自己写一个，但是又无从下手，看了您的这个项目虽有所启发，但您的项目有些复杂，我还是有太多不理解的地方，不知您是否有时间指导一下呢？我前期想写一个一条舰艇防导弹攻击的场景，算法方面看的资料也不少了，就是环境这块不知该怎么搞。我现在在研究您的environment，如果您有时间指导学生一下那万分感谢了。

**Comment by leonfg** [comment]
> 
> 
> 您好，我自学RL有一段时间了，因为对海战感兴趣，一直想把RL应用在海战上，但是gym上没有合适的环境，一直想自己写一个，但是又无从下手，看了您的这个项目虽有所启发，但您的项目有些复杂，我还是有太多不理解的地方，不知您是否有时间指导一下呢？我前期想写一个一条舰艇防导弹攻击的场景，算法方面看的资料也不少了，就是环境这块不知该怎么搞。我现在在研究您的environment，如果您有时间指导学生一下那万分感谢了。

联系gaofang@cetc.com.cn
